---
deployment:
  tasks:
    - export DEPLOYPATH=/home/navizaft/public_html/
    - /bin/cp -R adminside $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R crewside $DEPLOYPATH
    - /bin/cp -R helpers $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R uploads $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
